#!/bin/sh

set -e

cd "$(dirname "$0")/.."

bundle check --path vendor/gems > /dev/null 2>&1 || \
    bundle install --local --path vendor/gems

git submodule sync --quiet
git submodule update --init
